// Generated by https://quicktype.io

export interface Media {
  alt: string
  caption: null | string
  created_at: string
  created_by: number
  description: null | string
  height: number | null
  id: number
  is_active: number
  is_thumbnail: number
  media_id: null | number
  name: string
  path: string
  size: number
  type: string
  updated_at: string
  updated_by: number
  url: string
  width: number | string
  updated_by_name: null | string
  created_by_name: null | string
  thumbnail: null | string
}

export interface UpdateMediaParams {
  alt: string
  description?: string | null
  caption?: string | null
}
